name: Startup Growth
favicon: null
layout_spectrum: 0.6866474105045199
typography_spectrum: 0.12008929927833378
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.535178774734959
  lightness: 0.22245840006507933
  saturation: 0.12216751580126584
  rhythmicContrast: 0.3257936805021018
purpose: []
